clear all;
close all;

% x_pred='AHCDFBHINDADBDCINNAEHBBADCEDDBDECHGENIHIEHECDFNEEI';
% x_true='AHCFFBGINDAFBDCINNAEHBBADCGNGBDDCHGEAIHIEHECFFNGEI';

x_pred='NEDNDDDDADCIGBEBDCEHGHHIFBHEAIDNDHIIDCBEENABEEDNAGNINNGHAEECINEDENDIFCDACECBFBHNEIIIGNABAGNIDBAGBEBB';
x_true='NDDCDNNDAFANGBGBFCEHGHHHGHFDAIDNFHIIECBDENIBEFGNAGIINIGHAEFCCCFDGCECGIEICENBEEHADIHCGAABIHCNDBAGBFBB';

j=0;
for i=1:length(x_pred)
    if x_pred(i)==x_true(i)
        j=j+1;
    end
end

disp(j*100/length(x_pred))